// Code generated by "enumer -type=MSGID"; DO NOT EDIT.

package msg

import (
	"fmt"
	"strings"
)

const _MSGIDName = "MSG_STARTMSG_PINGMSG_PONGMSG_HANDSHAKEMSG_REGISTERROUTERMSG_SNAPSHOTSUBSMSG_SUBMSG_UNSUBMSG_PUBMSG_ROUTEPUBMSG_NEWROUTEMSG_REMOTEROUTEADDSUBMSG_REMOTEROUTEADDUNSUBMSG_CURALLROUTES"

var _MSGIDIndex = [...]uint8{0, 9, 17, 25, 38, 56, 72, 79, 88, 95, 107, 119, 140, 163, 179}

const _MSGIDLowerName = "msg_startmsg_pingmsg_pongmsg_handshakemsg_registerroutermsg_snapshotsubsmsg_submsg_unsubmsg_pubmsg_routepubmsg_newroutemsg_remoterouteaddsubmsg_remoterouteaddunsubmsg_curallroutes"

func (i MSGID) String() string {
	i -= 1
	if i < 0 || i >= MSGID(len(_MSGIDIndex)-1) {
		return fmt.Sprintf("MSGID(%d)", i+1)
	}
	return _MSGIDName[_MSGIDIndex[i]:_MSGIDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MSGIDNoOp() {
	var x [1]struct{}
	_ = x[MSG_START-(1)]
	_ = x[MSG_PING-(2)]
	_ = x[MSG_PONG-(3)]
	_ = x[MSG_HANDSHAKE-(4)]
	_ = x[MSG_REGISTERROUTER-(5)]
	_ = x[MSG_SNAPSHOTSUBS-(6)]
	_ = x[MSG_SUB-(7)]
	_ = x[MSG_UNSUB-(8)]
	_ = x[MSG_PUB-(9)]
	_ = x[MSG_ROUTEPUB-(10)]
	_ = x[MSG_NEWROUTE-(11)]
	_ = x[MSG_REMOTEROUTEADDSUB-(12)]
	_ = x[MSG_REMOTEROUTEADDUNSUB-(13)]
	_ = x[MSG_CURALLROUTES-(14)]
}

var _MSGIDValues = []MSGID{MSG_START, MSG_PING, MSG_PONG, MSG_HANDSHAKE, MSG_REGISTERROUTER, MSG_SNAPSHOTSUBS, MSG_SUB, MSG_UNSUB, MSG_PUB, MSG_ROUTEPUB, MSG_NEWROUTE, MSG_REMOTEROUTEADDSUB, MSG_REMOTEROUTEADDUNSUB, MSG_CURALLROUTES}

var _MSGIDNameToValueMap = map[string]MSGID{
	_MSGIDName[0:9]:          MSG_START,
	_MSGIDLowerName[0:9]:     MSG_START,
	_MSGIDName[9:17]:         MSG_PING,
	_MSGIDLowerName[9:17]:    MSG_PING,
	_MSGIDName[17:25]:        MSG_PONG,
	_MSGIDLowerName[17:25]:   MSG_PONG,
	_MSGIDName[25:38]:        MSG_HANDSHAKE,
	_MSGIDLowerName[25:38]:   MSG_HANDSHAKE,
	_MSGIDName[38:56]:        MSG_REGISTERROUTER,
	_MSGIDLowerName[38:56]:   MSG_REGISTERROUTER,
	_MSGIDName[56:72]:        MSG_SNAPSHOTSUBS,
	_MSGIDLowerName[56:72]:   MSG_SNAPSHOTSUBS,
	_MSGIDName[72:79]:        MSG_SUB,
	_MSGIDLowerName[72:79]:   MSG_SUB,
	_MSGIDName[79:88]:        MSG_UNSUB,
	_MSGIDLowerName[79:88]:   MSG_UNSUB,
	_MSGIDName[88:95]:        MSG_PUB,
	_MSGIDLowerName[88:95]:   MSG_PUB,
	_MSGIDName[95:107]:       MSG_ROUTEPUB,
	_MSGIDLowerName[95:107]:  MSG_ROUTEPUB,
	_MSGIDName[107:119]:      MSG_NEWROUTE,
	_MSGIDLowerName[107:119]: MSG_NEWROUTE,
	_MSGIDName[119:140]:      MSG_REMOTEROUTEADDSUB,
	_MSGIDLowerName[119:140]: MSG_REMOTEROUTEADDSUB,
	_MSGIDName[140:163]:      MSG_REMOTEROUTEADDUNSUB,
	_MSGIDLowerName[140:163]: MSG_REMOTEROUTEADDUNSUB,
	_MSGIDName[163:179]:      MSG_CURALLROUTES,
	_MSGIDLowerName[163:179]: MSG_CURALLROUTES,
}

var _MSGIDNames = []string{
	_MSGIDName[0:9],
	_MSGIDName[9:17],
	_MSGIDName[17:25],
	_MSGIDName[25:38],
	_MSGIDName[38:56],
	_MSGIDName[56:72],
	_MSGIDName[72:79],
	_MSGIDName[79:88],
	_MSGIDName[88:95],
	_MSGIDName[95:107],
	_MSGIDName[107:119],
	_MSGIDName[119:140],
	_MSGIDName[140:163],
	_MSGIDName[163:179],
}

// MSGIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MSGIDString(s string) (MSGID, error) {
	if val, ok := _MSGIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MSGIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MSGID values", s)
}

// MSGIDValues returns all values of the enum
func MSGIDValues() []MSGID {
	return _MSGIDValues
}

// MSGIDStrings returns a slice of all String values of the enum
func MSGIDStrings() []string {
	strs := make([]string, len(_MSGIDNames))
	copy(strs, _MSGIDNames)
	return strs
}

// IsAMSGID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MSGID) IsAMSGID() bool {
	for _, v := range _MSGIDValues {
		if i == v {
			return true
		}
	}
	return false
}
